### ISSUE TITLE
Задание с полётом тела

### ISSUE THREAD

**Issue by TrubnikovGI** [TrubnikovGI/WPF2021#1]
Здравствуйте, я опубликовал первое задание (с названием Balistic).

**Comment by TrubnikovGI** [comment]
Так, извиняюсь я только сейчас понял, что необходимо вас добавить в данную issue чтобы вы увидели, надеюсь видно что само задание я выкладывал в срок.

**Comment by justjune** [comment]
См. Успеваемость
