### ISSUE TITLE
Нерациональный расчет: зачем рассчитывать проекции скорости на каждом шаге и повторять расчет шага?

### ISSUE THREAD

**Issue by justjune** [TrubnikovGI/WPF2021#4]
https://github.com/TrubnikovGI/WPF2021/blob/4d2b6390c9e8baf0852c09ed1a1d8a9a4cbd5a06/Balistic/Program.cs#L25

**Comment by TrubnikovGI** [comment]
исправил при переходе к методу Эйлера

**Comment by justjune** [comment]
См. Успеваемость.
